"""
Test runner — executes pytest on the sample project and parses results.
"""
from __future__ import annotations
import subprocess
import sys
import tempfile
import os
import re
from pathlib import Path

from backend.models.schemas import TestRunResult

ROOT = Path(__file__).resolve().parent.parent.parent

# On Windows, subprocesses launched from threads inside uvicorn inherit the
# console's Ctrl-C signal group and receive a KeyboardInterrupt during Python
# startup before any code can run.  Creating a new process group detaches the
# child from the parent's signal handler so Python can initialise normally.
_SUBPROCESS_FLAGS = (
    subprocess.CREATE_NEW_PROCESS_GROUP
    if sys.platform == "win32" and hasattr(subprocess, "CREATE_NEW_PROCESS_GROUP")
    else 0
)


def run_existing_tests() -> TestRunResult:
    """Run the sample_project test suite and return structured results."""
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "sample_project/tests/", "-v", "--tb=short", "--no-header"],
        capture_output=True,
        text=True,
        cwd=str(ROOT),
        creationflags=_SUBPROCESS_FLAGS,
    )
    return _parse_pytest_output(result.stdout + result.stderr, result.returncode)


def run_generated_tests(generated_code: str) -> TestRunResult:
    """Write generated test code to a temp file and run it."""
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".py",
        prefix="cg_generated_",
        dir=str(ROOT / "sample_project" / "tests"),
        delete=False,
    ) as f:
        f.write("# Auto-generated by ChangeGuard\n")
        f.write(generated_code)
        tmp_path = f.name

    try:
        result = subprocess.run(
            [sys.executable, "-m", "pytest", tmp_path, "-v", "--tb=short", "--no-header"],
            capture_output=True,
            text=True,
            cwd=str(ROOT),
            creationflags=_SUBPROCESS_FLAGS,
        )
        return _parse_pytest_output(result.stdout + result.stderr, result.returncode)
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass


def _parse_pytest_output(output: str, returncode: int) -> TestRunResult:
    passed = len(re.findall(r" PASSED", output))
    failed = len(re.findall(r" FAILED", output))
    errors = len(re.findall(r" ERROR", output))

    # Also try to extract summary line: "3 passed, 1 failed"
    summary_match = re.search(r"(\d+) passed", output)
    if summary_match and passed == 0:
        passed = int(summary_match.group(1))
    fail_match = re.search(r"(\d+) failed", output)
    if fail_match and failed == 0:
        failed = int(fail_match.group(1))
    err_match = re.search(r"(\d+) error", output)
    if err_match and errors == 0:
        errors = int(err_match.group(1))

    return TestRunResult(
        passed=passed,
        failed=failed,
        errors=errors,
        output=output[-4000:] if len(output) > 4000 else output,
    )
